// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using PricePulse.Data;

#nullable disable

namespace PricePulse.Migrations
{
    [DbContext(typeof(PriceContext))]
    [Migration("20260707080613_AddReferenceSeries")]
    partial class AddReferenceSeries
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "9.0.6");

            modelBuilder.Entity("PricePulse.Data.Observation", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateOnly>("Date")
                        .HasColumnType("TEXT");

                    b.Property<string>("SeriesId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<decimal?>("Value")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("SeriesId", "Date")
                        .IsUnique();

                    b.ToTable("Observations");
                });

            modelBuilder.Entity("PricePulse.Data.Series", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("TEXT");

                    b.Property<string>("Icon")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsReference")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Units")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Series");

                    b.HasData(
                        new
                        {
                            Id = "APU0000708111",
                            Icon = "egg",
                            IsReference = false,
                            Name = "Eggs",
                            Units = "per dozen"
                        },
                        new
                        {
                            Id = "APU0000709112",
                            Icon = "svg:milk",
                            IsReference = false,
                            Name = "Milk",
                            Units = "per gallon"
                        },
                        new
                        {
                            Id = "APU000074714",
                            Icon = "local_gas_station",
                            IsReference = false,
                            Name = "Gasoline",
                            Units = "per gallon"
                        },
                        new
                        {
                            Id = "APU000072610",
                            Icon = "bolt",
                            IsReference = false,
                            Name = "Electricity",
                            Units = "per kWh"
                        },
                        new
                        {
                            Id = "APU0000702111",
                            Icon = "bakery_dining",
                            IsReference = false,
                            Name = "Bread",
                            Units = "per pound"
                        },
                        new
                        {
                            Id = "APU0000703112",
                            Icon = "lunch_dining",
                            IsReference = false,
                            Name = "Ground Beef",
                            Units = "per pound"
                        },
                        new
                        {
                            Id = "CPIAUCNS",
                            Icon = "trending_up",
                            IsReference = true,
                            Name = "Consumer Price Index",
                            Units = "index (1982-84=100)"
                        },
                        new
                        {
                            Id = "CEU0500000008",
                            Icon = "payments",
                            IsReference = true,
                            Name = "Average Hourly Earnings",
                            Units = "per hour"
                        });
                });

            modelBuilder.Entity("PricePulse.Data.Observation", b =>
                {
                    b.HasOne("PricePulse.Data.Series", "Series")
                        .WithMany("Observations")
                        .HasForeignKey("SeriesId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Series");
                });

            modelBuilder.Entity("PricePulse.Data.Series", b =>
                {
                    b.Navigation("Observations");
                });
#pragma warning restore 612, 618
        }
    }
}
