// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using PricePulse.Data;

#nullable disable

namespace PricePulse.Migrations
{
    [DbContext(typeof(PriceContext))]
    [Migration("20260702211627_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "9.0.6");

            modelBuilder.Entity("PricePulse.Models.Observation", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateOnly>("Date")
                        .HasColumnType("TEXT");

                    b.Property<string>("SeriesId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<decimal?>("Value")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("SeriesId", "Date")
                        .IsUnique();

                    b.ToTable("Observations");
                });

            modelBuilder.Entity("PricePulse.Models.Series", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Units")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Series");

                    b.HasData(
                        new
                        {
                            Id = "APU0000708111",
                            Name = "Eggs",
                            Units = "per dozen"
                        },
                        new
                        {
                            Id = "APU0000709112",
                            Name = "Milk",
                            Units = "per gallon"
                        },
                        new
                        {
                            Id = "APU000074714",
                            Name = "Gasoline",
                            Units = "per gallon"
                        },
                        new
                        {
                            Id = "APU000072610",
                            Name = "Electricity",
                            Units = "per kWh"
                        },
                        new
                        {
                            Id = "APU0000702111",
                            Name = "Bread",
                            Units = "per pound"
                        },
                        new
                        {
                            Id = "APU0000703112",
                            Name = "Ground Beef",
                            Units = "per pound"
                        });
                });

            modelBuilder.Entity("PricePulse.Models.Observation", b =>
                {
                    b.HasOne("PricePulse.Models.Series", "Series")
                        .WithMany("Observations")
                        .HasForeignKey("SeriesId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Series");
                });

            modelBuilder.Entity("PricePulse.Models.Series", b =>
                {
                    b.Navigation("Observations");
                });
#pragma warning restore 612, 618
        }
    }
}
