// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using PricePulse.Data;

#nullable disable

namespace PricePulse.Migrations
{
    [DbContext(typeof(PriceContext))]
    [Migration("20260709170934_SwitchGroceryIconsToLucide")]
    partial class SwitchGroceryIconsToLucide
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "9.0.6");

            modelBuilder.Entity("PricePulse.Models.Observation", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateOnly>("Date")
                        .HasColumnType("TEXT");

                    b.Property<string>("SeriesId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<decimal?>("Value")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("SeriesId", "Date")
                        .IsUnique();

                    b.ToTable("Observations");
                });

            modelBuilder.Entity("PricePulse.Models.Series", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("TEXT");

                    b.Property<int>("Category")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Icon")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsReference")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Kind")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Units")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Series");

                    b.HasData(
                        new
                        {
                            Id = "APU0000708111",
                            Category = 0,
                            Icon = "egg",
                            IsReference = false,
                            Kind = 0,
                            Name = "Eggs",
                            Units = "per dozen"
                        },
                        new
                        {
                            Id = "APU0000709112",
                            Category = 0,
                            Icon = "lucide:milk",
                            IsReference = false,
                            Kind = 0,
                            Name = "Milk",
                            Units = "per gallon"
                        },
                        new
                        {
                            Id = "APU0000702111",
                            Category = 0,
                            Icon = "bakery_dining",
                            IsReference = false,
                            Kind = 0,
                            Name = "Bread",
                            Units = "per pound"
                        },
                        new
                        {
                            Id = "APU0000703112",
                            Category = 0,
                            Icon = "lunch_dining",
                            IsReference = false,
                            Kind = 0,
                            Name = "Ground Beef",
                            Units = "per pound"
                        },
                        new
                        {
                            Id = "APU0000706111",
                            Category = 0,
                            Icon = "lucide:drumstick",
                            IsReference = false,
                            Kind = 0,
                            Name = "Chicken",
                            Units = "per pound"
                        },
                        new
                        {
                            Id = "APU0000717311",
                            Category = 0,
                            Icon = "coffee",
                            IsReference = false,
                            Kind = 0,
                            Name = "Coffee",
                            Units = "per pound"
                        },
                        new
                        {
                            Id = "APU0000711211",
                            Category = 0,
                            Icon = "lucide:banana",
                            IsReference = false,
                            Kind = 0,
                            Name = "Bananas",
                            Units = "per pound"
                        },
                        new
                        {
                            Id = "APU0000701312",
                            Category = 0,
                            Icon = "rice_bowl",
                            IsReference = false,
                            Kind = 0,
                            Name = "Rice",
                            Units = "per pound"
                        },
                        new
                        {
                            Id = "APU0000712311",
                            Category = 0,
                            Icon = "eco",
                            IsReference = false,
                            Kind = 0,
                            Name = "Tomatoes",
                            Units = "per pound"
                        },
                        new
                        {
                            Id = "APU000074714",
                            Category = 1,
                            Icon = "local_gas_station",
                            IsReference = false,
                            Kind = 0,
                            Name = "Gasoline",
                            Units = "per gallon"
                        },
                        new
                        {
                            Id = "APU000072610",
                            Category = 1,
                            Icon = "bolt",
                            IsReference = false,
                            Kind = 0,
                            Name = "Electricity",
                            Units = "per kWh"
                        },
                        new
                        {
                            Id = "MSPUS",
                            Category = 2,
                            Icon = "home",
                            IsReference = false,
                            Kind = 0,
                            Name = "Median Home Price",
                            Units = "U.S. median · MSPUS"
                        },
                        new
                        {
                            Id = "CUUR0000SEHA",
                            Category = 2,
                            Icon = "apartment",
                            IsReference = false,
                            Kind = 1,
                            Name = "Rent",
                            Units = "index (1982-84=100)"
                        },
                        new
                        {
                            Id = "CUUR0000SEEB",
                            Category = 3,
                            Icon = "school",
                            IsReference = false,
                            Kind = 1,
                            Name = "Tuition",
                            Units = "index (1982-84=100)"
                        },
                        new
                        {
                            Id = "CPIMEDNS",
                            Category = 4,
                            Icon = "medical_services",
                            IsReference = false,
                            Kind = 1,
                            Name = "Medical Care",
                            Units = "index (1982-84=100)"
                        },
                        new
                        {
                            Id = "CPIAPPNS",
                            Category = 5,
                            Icon = "checkroom",
                            IsReference = false,
                            Kind = 1,
                            Name = "Clothing",
                            Units = "index (1982-84=100)"
                        },
                        new
                        {
                            Id = "CUUR0000SERE01",
                            Category = 5,
                            Icon = "toys",
                            IsReference = false,
                            Kind = 1,
                            Name = "Toys",
                            Units = "index (1982-84=100)"
                        },
                        new
                        {
                            Id = "CUUR0000SEEE",
                            Category = 5,
                            Icon = "devices",
                            IsReference = false,
                            Kind = 1,
                            Name = "Electronics",
                            Units = "index (Dec 2024=100)"
                        },
                        new
                        {
                            Id = "CEU0500000008",
                            Category = 6,
                            Icon = "payments",
                            IsReference = false,
                            Kind = 2,
                            Name = "Non-Executive Wage",
                            Units = "per hour"
                        },
                        new
                        {
                            Id = "OPHNFB",
                            Category = 7,
                            Icon = "speed",
                            IsReference = false,
                            Kind = 3,
                            Name = "Productivity",
                            Units = "output/hour · index (2017=100)"
                        },
                        new
                        {
                            Id = "CPIAUCNS",
                            Category = 2,
                            Icon = "trending_up",
                            IsReference = true,
                            Kind = 1,
                            Name = "Consumer Price Index",
                            Units = "index (1982-84=100)"
                        });
                });

            modelBuilder.Entity("PricePulse.Models.Observation", b =>
                {
                    b.HasOne("PricePulse.Models.Series", "Series")
                        .WithMany("Observations")
                        .HasForeignKey("SeriesId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Series");
                });

            modelBuilder.Entity("PricePulse.Models.Series", b =>
                {
                    b.Navigation("Observations");
                });
#pragma warning restore 612, 618
        }
    }
}
